export const AREAS_ES = {
  Uruguayan: 'Uruguay',
  Turkish: 'Turquía',
  'Saudi Arabian': 'Arabia Saudita',
  Argentina: 'Argentina',
  Spanish: 'España',
  Japanese: 'Japón',
  Croatian: 'Croacia',
  Ukrainian: 'Ucrania',
  Egyptian: 'Egipto',
  Filipino: 'Filipinas',
  Polish: 'Polonia',
  'United States': 'Estados Unidos',
  India: 'India',
  Canadian: 'Canadá',
};

export const INGREDIENTES_ES = {
  Sugar: 'Azúcar',
  Milk: 'Leche',
  'vanilla pod': 'Vaina de vainilla',
  'Egg Yolks': 'Yemas de huevo',
  Egg: 'Huevo',
  'Dulce de leche': 'Dulce de leche',
  Tomato: 'Tomate',
  'Romano Pepper': 'Pimiento romano',
  'Green Chilli': 'Chile verde',
  Onion: 'Cebolla',
  Garlic: 'Ajo',
  Parsley: 'Perejil',
  'Red Pepper Paste': 'Pasta de pimiento rojo',
  'Tomato Puree': 'Puré de tomate',
  'Pomegranate Molasses': 'Melaza de granada',
  'Pul Biber': 'Pul biber (chile turco)',
  Sumac: 'Sumac',
  'Dried Mint': 'Menta seca',
  'Extra Virgin Olive Oil': 'Aceite de oliva virgen extra',
  Chicken: 'Pollo',
  Rice: 'Arroz',
  'Green Pepper': 'Pimiento verde',
  'Red Pepper': 'Pimiento rojo',
  Mushrooms: 'Champiñones',
  Sweetcorn: 'Maíz dulce',
  Carrots: 'Zanahorias',
  Raisins: 'Pasas',
  Turmeric: 'Cúrcuma',
  'Kabse Spice': 'Especias kabsa',
  Salt: 'Sal',
  'Black Pepper': 'Pimienta negra',
  'Mixed Beef Cuts': 'Cortes mixtos de res',
  Chorizo: 'Chorizo',
  Morcilla: 'Morcilla',
  Bread: 'Pan',
  'Olive Oil': 'Aceite de oliva',
  Pork: 'Cerdo',
  'Sushi Rice': 'Arroz para sushi',
  'Rice wine': 'Vino de arroz',
  'Caster Sugar': 'Azúcar glass',
  Mayonnaise: 'Mayonesa',
  'Soy Sauce': 'Salsa de soja',
  Cucumber: 'Pepino',
  Potatoes: 'Papas',
  Butter: 'Mantequilla',
  Cheese: 'Queso',
  'Red Chilli Flakes': 'Hojuelas de chile rojo',
  'Natural Yoghurt': 'Yogur natural',
  'Lemon Juice': 'Jugo de limón',
  'Dried white corn': 'Maíz blanco seco',
  'Dried white beans': 'Porotos blancos secos',
  Pumpkin: 'Zapallo',
  Beef: 'Carne de res',
  Paprika: 'Pimentón',
  Pepper: 'Pimienta',
  'Filo Pastry': 'Masa filo',
  'Minced Beef': 'Carne picada',
  Oil: 'Aceite',
  'Whole Milk': 'Leche entera',
  Cornstarch: 'Maicena',
  'Ground Cardomom': 'Cardamomo molido',
  'Rose water': 'Agua de rosas',
  Almonds: 'Almendras',
  Pistachio: 'Pistachos',
  Lentils: 'Lentejas',
  'Tomato Puree': 'Puré de tomate',
  Cumin: 'Comino',
  Mint: 'Menta',
  Thyme: 'Tomillo',
  'Red Pepper Flakes': 'Hojuelas de pimiento rojo',
  'Vegetable Stock': 'Caldo de verduras',
  Water: 'Agua',
  'Sea Salt': 'Sal marina',
  'Beef Shin': 'Chamberete de res',
  'Bay Leaf': 'Hoja de laurel',
  'Sunflower Oil': 'Aceite de girasol',
  Beetroot: 'Remolacha',
  'Tinned Tomatos': 'Tomates enlatados',
  Prunes: 'Ciruelas pasas',
  'White Cabbage': 'Repollo blanco',
  'Kidney Beans': 'Porotos rojos',
  'Creme Fraiche': 'Crème fraîche',
  Dill: 'Eneldo',
  'Crusty Bread': 'Pan crujiente',
  Chickpeas: 'Garbanzos',
  'Tahini Paste': 'Pasta de tahini',
  'Garlic Clove': 'Diente de ajo',
  'Greek Yogurt': 'Yogur griego',
  Lemon: 'Limón',
  Knafeh: 'Kadaif',
  'Unsalted Butter': 'Mantequilla sin sal',
  'Yellow Food Colouring': 'Colorante amarillo',
  Mozzarella: 'Mozzarella',
  'Cream Cheese': 'Queso crema',
  'Corn Flour': 'Harina de maíz',
  'Broad Beans': 'Habas',
  'Spring Onions': 'Cebollín',
  'Baking Powder': 'Polvo de hornear',
  'Cayenne Pepper': 'Pimienta de cayena',
  Flour: 'Harina',
  'Vegetable Oil': 'Aceite vegetal',
  'Soy Sauce': 'Salsa de soja',
  'Olive Oil': 'Aceite de oliva',
  'Raw tiger prawns': 'Langostinos crudos',
  'Dry sherry': 'Jerez seco',
  Mussels: 'Mejillones',
  Saffron: 'Azafrán',
  Squid: 'Calamar',
  'Paella Rice': 'Arroz para paella',
  'Broad Beans': 'Habas',
  'Lemon Zest': 'Ralladura de limón',
  'Chickpea Flour': 'Harina de garbanzo',
  Yeast: 'Levadura',
  'Sunflower Oil': 'Aceite de girasol',
  'Poppy Seeds': 'Semillas de amapola',
  'Sesame Seed Burger Buns': 'Panes de hamburguesa con sésamo',
  'White Wine Vinegar': 'Vinagre de vino blanco',
  Mustard: 'Mostaza',
  'Onion Salt': 'Sal de cebolla',
  'Garlic Powder': 'Ajo en polvo',
  'Ground Cumin': 'Comino molido',
  'Ground Coriander': 'Cilantro molido',
  'Toor dal': 'Lenteja toor',
  Ghee: 'Ghee',
  'Chopped tomatoes': 'Tomates picados',
  'Mustard Seeds': 'Semillas de mostaza',
  'Green Chilli': 'Chile verde',
  Cilantro: 'Cilantro',
  'Brown Lentils': 'Lentejas marrones',
  Coriander: 'Cilantro',
  Macaroni: 'Macarrones',
  'Beef Gravy': 'Salsa de carne',
  'Cheese Curds': 'Cuajada de queso',
  'Strong white bread flour': 'Harina de trigo fuerte',
  'Iceberg Lettuce': 'Lechuga iceberg',
  'Dill Pickles': 'Pepinillos en vinagre',
  'Chickpea Flour': 'Harina de garbanzo',
};

const MEDIDAS_FRASES = [
  ['To taste', 'Al gusto'],
  ['To serve', 'Para servir'],
  ['Pinch', 'Pizca'],
  ['Handful', 'Un puñado'],
  ['Dash', 'Un chorrito'],
  ['As required', 'Según necesidad'],
  ['Bunch', 'Un manojo'],
  ['cloves minced', 'dientes picados'],
  ['Beaten', 'Batidos'],
  ['thin cut', 'corte fino'],
  ['chopped', 'picado'],
  ['sliced', 'en rodajas'],
  ['Can', 'Lata'],
  ['Spinkling', 'Un poco'],
  ['Sprinking', 'Un poco'],
  ['Juice of half', 'Jugo de medio'],
  ['1 Packet', '1 paquete'],
  ['Large', 'Grande'],
  ['medium', 'mediano'],
  ['small', 'pequeño'],
  ['cups', 'tazas'],
  ['cup', 'taza'],
  ['tblsp', 'cda'],
  ['tbs', 'cda'],
  ['tsp', 'cdta'],
  ['tablespoon', 'cucharada'],
  ['teaspoon', 'cucharadita'],
  ['clove', 'diente'],
  ['cloves', 'dientes'],
  ['minced', 'picado'],
  ['Diced', 'En cubos'],
  ['grams', 'g'],
  ['g ', 'g '],
  ['ml', 'ml'],
  ['kg', 'kg'],
  ['lb', 'lb'],
];

export function traducirIngrediente(nombre) {
  if (!nombre) return '';
  const exact = INGREDIENTES_ES[nombre];
  if (exact) return exact;
  const norm = nombre.trim();
  for (const [en, es] of Object.entries(INGREDIENTES_ES)) {
    if (norm.toLowerCase() === en.toLowerCase()) return es;
  }
  return nombre;
}

export function traducirMedida(medida) {
  if (!medida) return '';
  let texto = String(medida).trim();
  for (const [en, es] of MEDIDAS_FRASES) {
    texto = texto.replace(new RegExp(en, 'gi'), es);
  }
  return texto;
}

export function traducirArea(area) {
  if (!area) return '';
  return AREAS_ES[area] || area;
}

export function traducirCategoria(categoria) {
  const map = {
    Vegetariano: 'Vegetariano',
    Pollo: 'Pollo',
    Carnes: 'Carnes',
    Variado: 'Variado',
    Mariscos: 'Mariscos',
    'Acompañamientos': 'Acompañamientos',
    Postres: 'Postres',
  };
  return map[categoria] || categoria;
}

export function formatearIngredienteEs(nombre, medida) {
  const etiqueta = traducirIngrediente(nombre);
  const cantidad = traducirMedida(medida);
  if (cantidad && cantidad !== 'Al gusto') return `${cantidad} de ${etiqueta}`;
  if (cantidad === 'Al gusto') return `${etiqueta} (al gusto)`;
  return etiqueta;
}

/** Traducciones al español para datos de MealDB / Supabase */
 
export const AREAS_ES = {
  Uruguayan: 'Uruguay',
  Turkish: 'Turquía',
  'Saudi Arabian': 'Arabia Saudita',
  Argentina: 'Argentina',
  Spanish: 'España',
  Japanese: 'Japón',
  Croatian: 'Croacia',
  Ukrainian: 'Ucrania',
  Egyptian: 'Egipto',
  Filipino: 'Filipinas',
  Polish: 'Polonia',
  'United States': 'Estados Unidos',
  India: 'India',
  Canadian: 'Canadá',
};

export const INGREDIENTES_ES = {
  Sugar: 'Azúcar',
  Milk: 'Leche',
  'vanilla pod': 'Vaina de vainilla',
  'Egg Yolks': 'Yemas de huevo',
  Egg: 'Huevo',
  'Dulce de leche': 'Dulce de leche',
  Tomato: 'Tomate',
  'Romano Pepper': 'Pimiento romano',
  'Green Chilli': 'Chile verde',
  Onion: 'Cebolla',
  Garlic: 'Ajo',
  Parsley: 'Perejil',
  'Red Pepper Paste': 'Pasta de pimiento rojo',
  'Tomato Puree': 'Puré de tomate',
  'Pomegranate Molasses': 'Melaza de granada',
  'Pul Biber': 'Pul biber (chile turco)',
  Sumac: 'Sumac',
  'Dried Mint': 'Menta seca',
  'Extra Virgin Olive Oil': 'Aceite de oliva virgen extra',
  Chicken: 'Pollo',
  Rice: 'Arroz',
  'Green Pepper': 'Pimiento verde',
  'Red Pepper': 'Pimiento rojo',
  Mushrooms: 'Champiñones',
  Sweetcorn: 'Maíz dulce',
  Carrots: 'Zanahorias',
  Raisins: 'Pasas',
  Turmeric: 'Cúrcuma',
  'Kabse Spice': 'Especias kabsa',
  Salt: 'Sal',
  'Black Pepper': 'Pimienta negra',
  'Mixed Beef Cuts': 'Cortes mixtos de res',
  Chorizo: 'Chorizo',
  Morcilla: 'Morcilla',
  Bread: 'Pan',
  'Olive Oil': 'Aceite de oliva',
  Pork: 'Cerdo',
  'Sushi Rice': 'Arroz para sushi',
  'Rice wine': 'Vino de arroz',
  'Caster Sugar': 'Azúcar glass',
  Mayonnaise: 'Mayonesa',
  'Soy Sauce': 'Salsa de soja',
  Cucumber: 'Pepino',
  Potatoes: 'Papas',
  Butter: 'Mantequilla',
  Cheese: 'Queso',
  'Red Chilli Flakes': 'Hojuelas de chile rojo',
  'Natural Yoghurt': 'Yogur natural',
  'Lemon Juice': 'Jugo de limón',
  'Dried white corn': 'Maíz blanco seco',
  'Dried white beans': 'Porotos blancos secos',
  Pumpkin: 'Zapallo',
  Beef: 'Carne de res',
  Paprika: 'Pimentón',
  Pepper: 'Pimienta',
  'Filo Pastry': 'Masa filo',
  'Minced Beef': 'Carne picada',
  Oil: 'Aceite',
  'Whole Milk': 'Leche entera',
  Cornstarch: 'Maicena',
  'Ground Cardomom': 'Cardamomo molido',
  'Rose water': 'Agua de rosas',
  Almonds: 'Almendras',
  Pistachio: 'Pistachos',
  Lentils: 'Lentejas',
  'Tomato Puree': 'Puré de tomate',
  Cumin: 'Comino',
  Mint: 'Menta',
  Thyme: 'Tomillo',
  'Red Pepper Flakes': 'Hojuelas de pimiento rojo',
  'Vegetable Stock': 'Caldo de verduras',
  Water: 'Agua',
  'Sea Salt': 'Sal marina',
  'Beef Shin': 'Chamberete de res',
  'Bay Leaf': 'Hoja de laurel',
  'Sunflower Oil': 'Aceite de girasol',
  Beetroot: 'Remolacha',
  'Tinned Tomatos': 'Tomates enlatados',
  Prunes: 'Ciruelas pasas',
  'White Cabbage': 'Repollo blanco',
  'Kidney Beans': 'Porotos rojos',
  'Creme Fraiche': 'Crème fraîche',
  Dill: 'Eneldo',
  'Crusty Bread': 'Pan crujiente',
  Chickpeas: 'Garbanzos',
  'Tahini Paste': 'Pasta de tahini',
  'Garlic Clove': 'Diente de ajo',
  'Greek Yogurt': 'Yogur griego',
  Lemon: 'Limón',
  Knafeh: 'Kadaif',
  'Unsalted Butter': 'Mantequilla sin sal',
  'Yellow Food Colouring': 'Colorante amarillo',
  Mozzarella: 'Mozzarella',
  'Cream Cheese': 'Queso crema',
  'Corn Flour': 'Harina de maíz',
  'Broad Beans': 'Habas',
  'Spring Onions': 'Cebollín',
  'Baking Powder': 'Polvo de hornear',
  'Cayenne Pepper': 'Pimienta de cayena',
  Flour: 'Harina',
  'Vegetable Oil': 'Aceite vegetal',
  'Soy Sauce': 'Salsa de soja',
  'Olive Oil': 'Aceite de oliva',
  'Raw tiger prawns': 'Langostinos crudos',
  'Dry sherry': 'Jerez seco',
  Mussels: 'Mejillones',
  Saffron: 'Azafrán',
  Squid: 'Calamar',
  'Paella Rice': 'Arroz para paella',
  'Broad Beans': 'Habas',
  'Lemon Zest': 'Ralladura de limón',
  'Chickpea Flour': 'Harina de garbanzo',
  Yeast: 'Levadura',
  'Sunflower Oil': 'Aceite de girasol',
  'Poppy Seeds': 'Semillas de amapola',
  'Sesame Seed Burger Buns': 'Panes de hamburguesa con sésamo',
  'White Wine Vinegar': 'Vinagre de vino blanco',
  Mustard: 'Mostaza',
  'Onion Salt': 'Sal de cebolla',
  'Garlic Powder': 'Ajo en polvo',
  'Ground Cumin': 'Comino molido',
  'Ground Coriander': 'Cilantro molido',
  'Toor dal': 'Lenteja toor',
  Ghee: 'Ghee',
  'Chopped tomatoes': 'Tomates picados',
  'Mustard Seeds': 'Semillas de mostaza',
  'Green Chilli': 'Chile verde',
  Cilantro: 'Cilantro',
  'Brown Lentils': 'Lentejas marrones',
  Coriander: 'Cilantro',
  Macaroni: 'Macarrones',
  'Beef Gravy': 'Salsa de carne',
  'Cheese Curds': 'Cuajada de queso',
  'Strong white bread flour': 'Harina de trigo fuerte',
  'Iceberg Lettuce': 'Lechuga iceberg',
  'Dill Pickles': 'Pepinillos en vinagre',
  'Chickpea Flour': 'Harina de garbanzo',
};

const MEDIDAS_FRASES = [
  ['To taste', 'Al gusto'],
  ['To serve', 'Para servir'],
  ['Pinch', 'Pizca'],
  ['Handful', 'Un puñado'],
  ['Dash', 'Un chorrito'],
  ['As required', 'Según necesidad'],
  ['Bunch', 'Un manojo'],
  ['cloves minced', 'dientes picados'],
  ['Beaten', 'Batidos'],
  ['thin cut', 'corte fino'],
  ['chopped', 'picado'],
  ['sliced', 'en rodajas'],
  ['Can', 'Lata'],
  ['Spinkling', 'Un poco'],
  ['Sprinking', 'Un poco'],
  ['Juice of half', 'Jugo de medio'],
  ['1 Packet', '1 paquete'],
  ['Large', 'Grande'],
  ['medium', 'mediano'],
  ['small', 'pequeño'],
  ['cups', 'tazas'],
  ['cup', 'taza'],
  ['tblsp', 'cda'],
  ['tbs', 'cda'],
  ['tsp', 'cdta'],
  ['tablespoon', 'cucharada'],
  ['teaspoon', 'cucharadita'],
  ['clove', 'diente'],
  ['cloves', 'dientes'],
  ['minced', 'picado'],
  ['Diced', 'En cubos'],
  ['grams', 'g'],
  ['g ', 'g '],
  ['ml', 'ml'],
  ['kg', 'kg'],
  ['lb', 'lb'],
];

export function traducirIngrediente(nombre) {
  if (!nombre) return '';
  const exact = INGREDIENTES_ES[nombre];
  if (exact) return exact;
  const norm = nombre.trim();
  for (const [en, es] of Object.entries(INGREDIENTES_ES)) {
    if (norm.toLowerCase() === en.toLowerCase()) return es;
  }
  return nombre;
}

export function traducirMedida(medida) {
  if (!medida) return '';
  let texto = String(medida).trim();
  for (const [en, es] of MEDIDAS_FRASES) {
    texto = texto.replace(new RegExp(en, 'gi'), es);
  }
  return texto;
}

export function traducirArea(area) {
  if (!area) return '';
  return AREAS_ES[area] || area;
}

export function traducirCategoria(categoria) {
  const map = {
    Vegetariano: 'Vegetariano',
    Pollo: 'Pollo',
    Carnes: 'Carnes',
    Variado: 'Variado',
    Mariscos: 'Mariscos',
    'Acompañamientos': 'Acompañamientos',
    Postres: 'Postres',
  };
  return map[categoria] || categoria;
}

export function formatearIngredienteEs(nombre, medida) {
  const etiqueta = traducirIngrediente(nombre);
  const cantidad = traducirMedida(medida);
  if (cantidad && cantidad !== 'Al gusto') return `${cantidad} de ${etiqueta}`;
  if (cantidad === 'Al gusto') return `${etiqueta} (al gusto)`;
  return etiqueta;
}/** Traducciones al español para datos de MealDB / Supabase */

export const AREAS_ES = {
  Uruguayan: 'Uruguay',
  Turkish: 'Turquía',
  'Saudi Arabian': 'Arabia Saudita',
  Argentina: 'Argentina',
  Spanish: 'España',
  Japanese: 'Japón',
  Croatian: 'Croacia',
  Ukrainian: 'Ucrania',
  Egyptian: 'Egipto',
  Filipino: 'Filipinas',
  Polish: 'Polonia',
  'United States': 'Estados Unidos',
  India: 'India',
  Canadian: 'Canadá',
};

export const INGREDIENTES_ES = {
  Sugar: 'Azúcar',
  Milk: 'Leche',
  'vanilla pod': 'Vaina de vainilla',
  'Egg Yolks': 'Yemas de huevo',
  Egg: 'Huevo',
  'Dulce de leche': 'Dulce de leche',
  Tomato: 'Tomate',
  'Romano Pepper': 'Pimiento romano',
  'Green Chilli': 'Chile verde',
  Onion: 'Cebolla',
  Garlic: 'Ajo',
  Parsley: 'Perejil',
  'Red Pepper Paste': 'Pasta de pimiento rojo',
  'Tomato Puree': 'Puré de tomate',
  'Pomegranate Molasses': 'Melaza de granada',
  'Pul Biber': 'Pul biber (chile turco)',
  Sumac: 'Sumac',
  'Dried Mint': 'Menta seca',
  'Extra Virgin Olive Oil': 'Aceite de oliva virgen extra',
  Chicken: 'Pollo',
  Rice: 'Arroz',
  'Green Pepper': 'Pimiento verde',
  'Red Pepper': 'Pimiento rojo',
  Mushrooms: 'Champiñones',
  Sweetcorn: 'Maíz dulce',
  Carrots: 'Zanahorias',
  Raisins: 'Pasas',
  Turmeric: 'Cúrcuma',
  'Kabse Spice': 'Especias kabsa',
  Salt: 'Sal',
  'Black Pepper': 'Pimienta negra',
  'Mixed Beef Cuts': 'Cortes mixtos de res',
  Chorizo: 'Chorizo',
  Morcilla: 'Morcilla',
  Bread: 'Pan',
  'Olive Oil': 'Aceite de oliva',
  Pork: 'Cerdo',
  'Sushi Rice': 'Arroz para sushi',
  'Rice wine': 'Vino de arroz',
  'Caster Sugar': 'Azúcar glass',
  Mayonnaise: 'Mayonesa',
  'Soy Sauce': 'Salsa de soja',
  Cucumber: 'Pepino',
  Potatoes: 'Papas',
  Butter: 'Mantequilla',
  Cheese: 'Queso',
  'Red Chilli Flakes': 'Hojuelas de chile rojo',
  'Natural Yoghurt': 'Yogur natural',
  'Lemon Juice': 'Jugo de limón',
  'Dried white corn': 'Maíz blanco seco',
  'Dried white beans': 'Porotos blancos secos',
  Pumpkin: 'Zapallo',
  Beef: 'Carne de res',
  Paprika: 'Pimentón',
  Pepper: 'Pimienta',
  'Filo Pastry': 'Masa filo',
  'Minced Beef': 'Carne picada',
  Oil: 'Aceite',
  'Whole Milk': 'Leche entera',
  Cornstarch: 'Maicena',
  'Ground Cardomom': 'Cardamomo molido',
  'Rose water': 'Agua de rosas',
  Almonds: 'Almendras',
  Pistachio: 'Pistachos',
  Lentils: 'Lentejas',
  'Tomato Puree': 'Puré de tomate',
  Cumin: 'Comino',
  Mint: 'Menta',
  Thyme: 'Tomillo',
  'Red Pepper Flakes': 'Hojuelas de pimiento rojo',
  'Vegetable Stock': 'Caldo de verduras',
  Water: 'Agua',
  'Sea Salt': 'Sal marina',
  'Beef Shin': 'Chamberete de res',
  'Bay Leaf': 'Hoja de laurel',
  'Sunflower Oil': 'Aceite de girasol',
  Beetroot: 'Remolacha',
  'Tinned Tomatos': 'Tomates enlatados',
  Prunes: 'Ciruelas pasas',
  'White Cabbage': 'Repollo blanco',
  'Kidney Beans': 'Porotos rojos',
  'Creme Fraiche': 'Crème fraîche',
  Dill: 'Eneldo',
  'Crusty Bread': 'Pan crujiente',
  Chickpeas: 'Garbanzos',
  'Tahini Paste': 'Pasta de tahini',
  'Garlic Clove': 'Diente de ajo',
  'Greek Yogurt': 'Yogur griego',
  Lemon: 'Limón',
  Knafeh: 'Kadaif',
  'Unsalted Butter': 'Mantequilla sin sal',
  'Yellow Food Colouring': 'Colorante amarillo',
  Mozzarella: 'Mozzarella',
  'Cream Cheese': 'Queso crema',
  'Corn Flour': 'Harina de maíz',
  'Broad Beans': 'Habas',
  'Spring Onions': 'Cebollín',
  'Baking Powder': 'Polvo de hornear',
  'Cayenne Pepper': 'Pimienta de cayena',
  Flour: 'Harina',
  'Vegetable Oil': 'Aceite vegetal',
  'Soy Sauce': 'Salsa de soja',
  'Olive Oil': 'Aceite de oliva',
  'Raw tiger prawns': 'Langostinos crudos',
  'Dry sherry': 'Jerez seco',
  Mussels: 'Mejillones',
  Saffron: 'Azafrán',
  Squid: 'Calamar',
  'Paella Rice': 'Arroz para paella',
  'Broad Beans': 'Habas',
  'Lemon Zest': 'Ralladura de limón',
  'Chickpea Flour': 'Harina de garbanzo',
  Yeast: 'Levadura',
  'Sunflower Oil': 'Aceite de girasol',
  'Poppy Seeds': 'Semillas de amapola',
  'Sesame Seed Burger Buns': 'Panes de hamburguesa con sésamo',
  'White Wine Vinegar': 'Vinagre de vino blanco',
  Mustard: 'Mostaza',
  'Onion Salt': 'Sal de cebolla',
  'Garlic Powder': 'Ajo en polvo',
  'Ground Cumin': 'Comino molido',
  'Ground Coriander': 'Cilantro molido',
  'Toor dal': 'Lenteja toor',
  Ghee: 'Ghee',
  'Chopped tomatoes': 'Tomates picados',
  'Mustard Seeds': 'Semillas de mostaza',
  'Green Chilli': 'Chile verde',
  Cilantro: 'Cilantro',
  'Brown Lentils': 'Lentejas marrones',
  Coriander: 'Cilantro',
  Macaroni: 'Macarrones',
  'Beef Gravy': 'Salsa de carne',
  'Cheese Curds': 'Cuajada de queso',
  'Strong white bread flour': 'Harina de trigo fuerte',
  'Iceberg Lettuce': 'Lechuga iceberg',
  'Dill Pickles': 'Pepinillos en vinagre',
  'Chickpea Flour': 'Harina de garbanzo',
};

const MEDIDAS_FRASES = [
  ['To taste', 'Al gusto'],
  ['To serve', 'Para servir'],
  ['Pinch', 'Pizca'],
  ['Handful', 'Un puñado'],
  ['Dash', 'Un chorrito'],
  ['As required', 'Según necesidad'],
  ['Bunch', 'Un manojo'],
  ['cloves minced', 'dientes picados'],
  ['Beaten', 'Batidos'],
  ['thin cut', 'corte fino'],
  ['chopped', 'picado'],
  ['sliced', 'en rodajas'],
  ['Can', 'Lata'],
  ['Spinkling', 'Un poco'],
  ['Sprinking', 'Un poco'],
  ['Juice of half', 'Jugo de medio'],
  ['1 Packet', '1 paquete'],
  ['Large', 'Grande'],
  ['medium', 'mediano'],
  ['small', 'pequeño'],
  ['cups', 'tazas'],
  ['cup', 'taza'],
  ['tblsp', 'cda'],
  ['tbs', 'cda'],
  ['tsp', 'cdta'],
  ['tablespoon', 'cucharada'],
  ['teaspoon', 'cucharadita'],
  ['clove', 'diente'],
  ['cloves', 'dientes'],
  ['minced', 'picado'],
  ['Diced', 'En cubos'],
  ['grams', 'g'],
  ['g ', 'g '],
  ['ml', 'ml'],
  ['kg', 'kg'],
  ['lb', 'lb'],
];
