/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#b2ed83',
        'inverse-primary': '#9dd770',
        'on-secondary-fixed-variant': '#604100',
        'tertiary-fixed': '#ffd8eb',
        'secondary-fixed-dim': '#f0be6d',
        'surface-variant': '#e1e4d8',
        'surface-container': '#edefe3',
        'secondary-container': '#fdc977',
        'primary-container': '#3b6d11',
        'on-error': '#ffffff',
        'on-secondary-container': '#775308',
        'on-secondary-fixed': '#281900',
        'secondary-fixed': '#ffdead',
        error: '#ba1a1a',
        outline: '#727969',
        'on-tertiary-fixed': '#3b002c',
        primary: '#275300',
        'on-tertiary-container': '#ffd0e8',
        'on-background': '#191d16',
        'inverse-on-surface': '#eff2e6',
        'error-container': '#ffdad6',
        'tertiary-container': '#9a407b',
        'outline-variant': '#c2c9b7',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#ffaedc',
        'on-tertiary-fixed-variant': '#7a255f',
        'primary-fixed': '#b8f389',
        'surface-bright': '#f8fbee',
        'inverse-surface': '#2e322a',
        'on-secondary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-surface-variant': '#42493b',
        'surface-tint': '#386a0e',
        'primary-fixed-dim': '#9dd770',
        'surface-container-high': '#e7e9dd',
        'on-tertiary': '#ffffff',
        'on-primary-fixed': '#0c2000',
        'surface-container-low': '#f2f5e9',
        'on-surface': '#191d16',
        'surface-container-highest': '#e1e4d8',
        'on-error-container': '#93000a',
        surface: '#f8fbee',
        'surface-dim': '#d9dbd0',
        'on-primary-fixed-variant': '#265100',
        background: '#f8fbee',
        tertiary: '#7d2762',
        secondary: '#7d570e',
      },
      spacing: {
        'stack-lg': '32px',
        'section-gap': '48px',
        'gutter-mobile': '16px',
        'stack-sm': '8px',
        base: '8px',
        'margin-mobile': '24px',
        'stack-md': '16px',
      },
      fontFamily: {
        brand: ['Fraunces', 'Georgia', 'serif'],
        'body-md': ['Nunito Sans', 'sans-serif'],
        'label-sm': ['Nunito Sans', 'sans-serif'],
        'label-lg': ['Nunito Sans', 'sans-serif'],
        'headline-md': ['Nunito Sans', 'sans-serif'],
        'body-lg': ['Nunito Sans', 'sans-serif'],
        'headline-xl': ['Nunito Sans', 'sans-serif'],
        'headline-lg': ['Nunito Sans', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '20px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '700' }],
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '800' }],
      },
      borderRadius: {
        card: '16px',
        't-card': '16px 16px 0 0',
        pill: '9999px',
        btn: '14px',
      },
      boxShadow: {
        card: '0 1px 3px rgba(25, 29, 22, 0.06), 0 4px 12px rgba(25, 29, 22, 0.04)',
        'card-hover': '0 4px 16px rgba(25, 29, 22, 0.08)',
        header: '0 1px 0 rgba(114, 121, 105, 0.2)',
        float: '0 8px 24px rgba(39, 83, 0, 0.12)',
      },
    },
  },
  plugins: [],
};
